name: board_manager
description: Project for tracking board games

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_performance: ^0.7.0+7
  firebase_crashlytics: ^2.1.1

  # UI
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0

  # Architecture
  surf_mwwm: ^2.0.2
  freezed_annotation: ^0.14.2
  rxdart: ^0.27.1

  # Logging
  surf_logger: ^1.0.1

  # Storage
  hive: ^2.0.4

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.4.1

  # Tools
  path_provider: ^2.0.2
  uuid: ^3.0.4
  json_annotation: ^4.1.0

  # Routing
  auto_route: 2.2.0

  # Network
  dio: ^4.0.0
  dio_firebase_performance: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Auto-gen
  hive_generator: ^1.1.0
  injectable_generator: ^1.4.1
  freezed: ^0.14.2
  auto_route_generator: ^2.1.0
  json_serializable: ^4.1.3

  # Linting
  surf_lint_rules: ^1.4.0

  # Build
  build_runner: ^2.0.6


flutter:
  uses-material-design: true
  assets:
    - assets/board_game_icon.png

